volumes:
  upload_volume:

services:
  uplewd:
    image: shindouj/uplewd:dev_build
    user: "0"
    links:
      - "db:mongo"
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - _JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - UPLEWD_MONGODB_HOST=mongo
      - UPLEWD_MONGODB_PORT=27017
      - UPLEWD_MONGODB_USER=mongo
      - UPLEWD_MONGODB_PASS=4kCAaX9cg4ChaPLhbNMS
      - UPLEWD_INSTANCE_NAME=Uplewd Dev
      - UPLEWD_GLOBAL_UPLOAD_LIMIT=250
      - UPLEWD_STORAGE_PATH=/upload
      - UPLEWD_STORAGE_FILENAME_MAX_LENGTH=16
      - UPLEWD_DELETE_ID_MAX_LENGTH=64
      - UPLEWD_HOST=http://127.0.0.1:8080
      - UPLEWD_FILE_HOST=http://1.2.3.4
      - UPLEWD_USER_TOKEN_MAX_LENGTH=128
    volumes:
      - upload_volume:/upload:Z
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=4kCAaX9cg4ChaPLhbNMS
  mongo-express:
    image: mongo-express
    links:
      - "db:mongo"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 4kCAaX9cg4ChaPLhbNMS
      ME_CONFIG_MONGODB_URL: mongodb://mongo:4kCAaX9cg4ChaPLhbNMS@mongo:27017/