spring:
  data:
    mongodb:
      host: ${UPLEWD_MONGODB_HOST}
      port: ${UPLEWD_MONGODB_PORT}
      username: ${UPLEWD_MONGODB_USER}
      password: ${UPLEWD_MONGODB_PASS}
      database: admin
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  tomcat:
    max-swallow-size: -1